<../../mkconfig

TARG=awk

OFILES=\
	b.$O\
	lex.$O\
	lib.$O\
	main.$O\
#	missing95.$O\
	parse.$O\
	proctab.$O\
	run.$O\
	tran.$O\
	ytab.$O\

HFILES=\
	awk.h\
	proto.h\
	ytab.h\

LIBS=bio			# order is important

CFLAGS=
LDFLAGS=$LDFLAGS

BIN=$ROOT/$OBJDIR/bin

<$ROOT/src/mkfiles/mkone-$SHELLTYPE
<mkfile-$HOSTMODEL
